// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1zy23fxWs7YTl43kLqSSsLO-Lj2y15cc',
    appId: '1:172582693839:web:22d8fdc47e82b3891240ba',
    messagingSenderId: '172582693839',
    projectId: 'gallery-dart',
    authDomain: 'gallery-dart.firebaseapp.com',
    databaseURL: 'https://gallery-dart-default-rtdb.firebaseio.com',
    storageBucket: 'gallery-dart.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6KazWGDSxutQub0U1fLaA9dVU2a98ssY',
    appId: '1:172582693839:android:9107a163066b78e31240ba',
    messagingSenderId: '172582693839',
    projectId: 'gallery-dart',
    databaseURL: 'https://gallery-dart-default-rtdb.firebaseio.com',
    storageBucket: 'gallery-dart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAymlFhNxjYjV4Gl_SkEuT-KmGoxG-Jnb0',
    appId: '1:172582693839:ios:6b21803aa19888781240ba',
    messagingSenderId: '172582693839',
    projectId: 'gallery-dart',
    databaseURL: 'https://gallery-dart-default-rtdb.firebaseio.com',
    storageBucket: 'gallery-dart.appspot.com',
    androidClientId: '172582693839-kj2odu6nvcjmqb669uplbor1nlshko03.apps.googleusercontent.com',
    iosClientId: '172582693839-6k72307qmof6cqs865dl1nufj22oa9kc.apps.googleusercontent.com',
    iosBundleId: 'com.example.dArtGallery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAymlFhNxjYjV4Gl_SkEuT-KmGoxG-Jnb0',
    appId: '1:172582693839:ios:6b21803aa19888781240ba',
    messagingSenderId: '172582693839',
    projectId: 'gallery-dart',
    databaseURL: 'https://gallery-dart-default-rtdb.firebaseio.com',
    storageBucket: 'gallery-dart.appspot.com',
    androidClientId: '172582693839-kj2odu6nvcjmqb669uplbor1nlshko03.apps.googleusercontent.com',
    iosClientId: '172582693839-6k72307qmof6cqs865dl1nufj22oa9kc.apps.googleusercontent.com',
    iosBundleId: 'com.example.dArtGallery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1zy23fxWs7YTl43kLqSSsLO-Lj2y15cc',
    appId: '1:172582693839:web:0013726877635cfd1240ba',
    messagingSenderId: '172582693839',
    projectId: 'gallery-dart',
    authDomain: 'gallery-dart.firebaseapp.com',
    databaseURL: 'https://gallery-dart-default-rtdb.firebaseio.com',
    storageBucket: 'gallery-dart.appspot.com',
  );
}
